#!/bin/bash
set -uo pipefail

function usage {
    cat <<EOF
This tool translates English text into Japanese with transtale-shell.
It also reads out the English text naturally using Google Cloud text-to-speech.

Usage:
    echo <translation target> | $(basename "${0}")

Options:
    -- <translate-args>   -- followed by the translate-shell argument. For example, -b, etc.
    --help, -h            print this
EOF
}

has_trans_args=0 # With translate-shell option argument -> 1
function get_option {
    case $1 in
        --) has_trans_args=1 && return 0 ;;
        --help|-h) usage && exit 0 ;;
        *) return 0 ;;
    esac
}

function get_phonetic_symbols {
    curl -sSL 'https://freeenglish.jp/convertp.php' \
    -H 'content-type: application/x-www-form-urlencoded' \
    --data-raw "englishtext=${1}&prontype=jones&fontsize=11" \
    --compressed \
    | pup '.ipa json{}' \
    | jq -r '.[] | if .children then .children = ([ .children[].text ] | join("")) else .children = "" end | .text = .text + .children | .text' \
    | xargs
}

[ $# -gt 0 ] && get_option "$1"
[ ${has_trans_args} -eq 1 ] && shift

sentences=""
[ -p /dev/stdin ] && sentences="$(cat -)" # Receive from standard input
sentences="$(echo "${sentences}" | sed -E s/\'\|\"\|\\.//g)"
if [ -z "${sentences}" ]; then
    usage
    exit 1
fi

SPELLS_DIR="$(dirname "$0")/spells"
readonly SPELLS_DIR
[ ! -e "${SPELLS_DIR}" ] && mkdir -p "${SPELLS_DIR}"

# shellcheck disable=SC2001
spell="$(echo "${sentences}" | sed s/' '/_/g)"
persent_encoding="$(echo "${sentences}" | jq -Rr '@uri')"

# Search cache
if [ -e "${SPELLS_DIR}/${spell}" ]; then
    printf "Show from cache\n\n"
    get_phonetic_symbols "${persent_encoding}"
    echo "${sentences}" | trans "$@"
    afplay "${SPELLS_DIR}/${spell}"
    exit 0
fi

# shellcheck disable=SC2046
cd $(dirname "$0") || exit
rm ./request.json ./synthesize-output-base64.txt ./synthesized-audio.mp3 >/dev/null 2>&1

# GCP's text-to-speech
cat <<-EOF >./request.json
{
  "input": {
    "text": "${sentences}"
  },
  "voice": {
    "languageCode": "en-gb",
    "name": "en-GB-Standard-A",
    "ssmlGender": "FEMALE"
  },
  "audioConfig": {
    "audioEncoding": "MP3",
    'effectsProfileId': ['telephony-class-application']
  }
}
EOF
curl -sSL -X POST \
-H "Authorization: Bearer $(gcloud auth application-default print-access-token)" \
-H "Content-Type: application/json; charset=utf-8" \
-d @request.json \
"https://texttospeech.googleapis.com/v1/text:synthesize" | jq -r '.audioContent' > ./synthesize-output-base64.txt
# Decode
base64 --decode synthesize-output-base64.txt > ./synthesized-audio.mp3

# Read & translate
get_phonetic_symbols "${persent_encoding}"
echo "${sentences}" | trans "$@"
afplay ./synthesized-audio.mp3

# Rename for cache
mv ./synthesized-audio.mp3 "${SPELLS_DIR}/${spell}"

# Return to the original directory
cd - >/dev/null || exit
